// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_list_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ProductListModelImpl _$$ProductListModelImplFromJson(
        Map<String, dynamic> json) =>
    _$ProductListModelImpl(
      status: (json['status'] as num?)?.toInt(),
      msg: json['msg'] as String?,
      list: json['list'] == null
          ? null
          : ListClass.fromJson(json['list'] as Map<String, dynamic>),
      pagesize: (json['pagesize'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$ProductListModelImplToJson(
        _$ProductListModelImpl instance) =>
    <String, dynamic>{
      'status': instance.status,
      'msg': instance.msg,
      'list': instance.list,
      'pagesize': instance.pagesize,
    };

_$ListClassImpl _$$ListClassImplFromJson(Map<String, dynamic> json) =>
    _$ListClassImpl(
      currentPage: (json['current_page'] as num?)?.toInt(),
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => Datum.fromJson(e as Map<String, dynamic>))
          .toList(),
      firstPageUrl: json['first_page_url'] as String?,
      from: (json['from'] as num?)?.toInt(),
      lastPage: (json['last_page'] as num?)?.toInt(),
      lastPageUrl: json['last_page_url'] as String?,
      links: (json['links'] as List<dynamic>?)
          ?.map((e) => Link.fromJson(e as Map<String, dynamic>))
          .toList(),
      nextPageUrl: json['next_page_url'],
      path: json['path'] as String?,
      perPage: (json['per_page'] as num?)?.toInt(),
      prevPageUrl: json['prev_page_url'],
      to: (json['to'] as num?)?.toInt(),
      total: (json['total'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$ListClassImplToJson(_$ListClassImpl instance) =>
    <String, dynamic>{
      'current_page': instance.currentPage,
      'data': instance.data,
      'first_page_url': instance.firstPageUrl,
      'from': instance.from,
      'last_page': instance.lastPage,
      'last_page_url': instance.lastPageUrl,
      'links': instance.links,
      'next_page_url': instance.nextPageUrl,
      'path': instance.path,
      'per_page': instance.perPage,
      'prev_page_url': instance.prevPageUrl,
      'to': instance.to,
      'total': instance.total,
    };

_$DatumImpl _$$DatumImplFromJson(Map<String, dynamic> json) => _$DatumImpl(
      id: (json['id'] as num?)?.toInt(),
      categoryId: (json['category_id'] as num?)?.toInt(),
      categoryName: json['category_name'] as String?,
      title: json['title'] as String?,
      bljg: json['bljg'] as String?,
      xmgm: (json['xmgm'] as num?)?.toInt(),
      xmjd: (json['xmjd'] as num?)?.toInt(),
      qtje: (json['qtje'] as num?)?.toInt(),
      zgje: json['zgje'] as String?,
      isgao: (json['isgao'] as num?)?.toInt(),
      ktje: json['ktje'],
      jyrsy: json['jyrsy'] as String?,
      tqsyyj: json['tqsyyj'] as String?,
      shijian: json['shijian'] as String?,
      pic: json['pic'] as String?,
      content: json['content'] as String?,
      qxdw: json['qxdw'] as String?,
      hkfs: (json['hkfs'] as num?)?.toInt(),
      cishu: json['cishu'],
      tzzt: (json['tzzt'] as num?)?.toInt(),
      isft: (json['isft'] as num?)?.toInt(),
      ftjl: (json['ftjl'] as num?)?.toInt(),
      level: (json['level'] as num?)?.toInt(),
      issy: (json['issy'] as num?)?.toInt(),
      issj: (json['issj'] as num?)?.toInt(),
      isdt: (json['isdt'] as num?)?.toInt(),
      iswj: (json['iswj'] as num?)?.toInt(),
      sort: (json['sort'] as num?)?.toInt(),
      tzyq: (json['tzyq'] as num?)?.toInt(),
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      cycle: (json['cycle'] as num?)?.toInt(),
      istzbug: (json['istzbug'] as num?)?.toInt(),
      isnew: (json['isnew'] as num?)?.toInt(),
      doubled: (json['doubled'] as num?)?.toInt(),
      countequity: (json['countequity'] as num?)?.toInt(),
      bugunmber: (json['bugunmber'] as num?)?.toInt(),
      ismake: (json['ismake'] as num?)?.toInt(),
      endingtime: json['endingtime'] as String?,
      isaouttm: (json['isaouttm'] as num?)?.toInt(),
      intervalTime: (json['interval_time'] as num?)?.toInt(),
      riseTime: json['rise_time'] as String?,
      frequency: (json['frequency'] as num?)?.toInt(),
      riseSettings: json['rise_settings'] as String?,
      rise: (json['rise'] as num?)?.toDouble(),
      coupon: json['coupon'] as String?,
      givecoupon: json['givecoupon'] as String?,
      oldmoney: json['oldmoney'] as String?,
      daikuan: json['daikuan'] as String?,
      equity: json['equity'] as String?,
      integralgive: json['integralgive'] as String?,
      nextintegralgive: (json['nextintegralgive'] as num?)?.toInt(),
      ticket: (json['ticket'] as num?)?.toInt(),
      beans: (json['beans'] as num?)?.toInt(),
      xxtcbl: json['xxtcbl'] as String?,
      xxtcbll: json['xxtcbll'] as String?,
      xxtcblll: json['xxtcblll'] as String?,
      xxtcbllll: json['xxtcbllll'] as String?,
      jiechuhetong: (json['jiechuhetong'] as num?)?.toInt(),
      discount: (json['discount'] as num?)?.toInt(),
      discountlist: json['discountlist'] as String?,
      capital: (json['capital'] as num?)?.toInt(),
      specialbenefits: json['specialbenefits'] as String?,
      bjzk: (json['bjzk'] as num?)?.toInt(),
      endtime: json['endtime'] as String?,
      zengsongid: (json['zengsongid'] as num?)?.toInt(),
      nextpid: (json['nextpid'] as num?)?.toInt(),
      jfpid: (json['jfpid'] as num?)?.toInt(),
      joining: (json['joining'] as num?)?.toInt(),
      organizer: (json['organizer'] as num?)?.toInt(),
      isgroup: (json['isgroup'] as num?)?.toInt(),
      isGroupLerver: (json['is_group_lerver'] as num?)?.toInt(),
      extmoney: (json['extmoney'] as num?)?.toInt(),
      extday: (json['extday'] as num?)?.toInt(),
      groupcbl: json['groupcbl'] as String?,
      isnorate: (json['isnorate'] as num?)?.toInt(),
      presale: (json['presale'] as num?)?.toInt(),
      firstbuy: (json['firstbuy'] as num?)?.toInt(),
      insurance: (json['insurance'] as num?)?.toInt(),
      ftAfterSuccess: (json['ft_after_success'] as num?)?.toInt(),
      presentLevel: (json['present_level'] as num?)?.toInt(),
      returnDividends: (json['return_dividends'] as num?)?.toInt(),
      returnCapital: (json['return_capital'] as num?)?.toInt(),
      isAggregatedAmount: (json['is_aggregated_amount'] as num?)?.toInt(),
      firstbuyText: json['firstbuy_text'] as String?,
      inviteOnly: (json['invite_only'] as num?)?.toInt(),
      dividendMethod: json['dividend_method'] as String?,
      ismake2: (json['ismake2'] as num?)?.toInt(),
      supportuse: (json['supportuse'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      investgift: (json['investgift'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      allreward: (json['allreward'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      demandTagList: json['demand_tag_list'] as List<dynamic>?,
      attentionTagList: (json['attention_tag_list'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      groupDemandTagList: json['group_demand_tag_list'] as List<dynamic>?,
      presentLevelName: json['present_level_name'] as String?,
      presentLevelText: json['present_level_text'] as String?,
      specialTagList: json['special_tag_list'] as List<dynamic>?,
    );

Map<String, dynamic> _$$DatumImplToJson(_$DatumImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'category_id': instance.categoryId,
      'category_name': instance.categoryName,
      'title': instance.title,
      'bljg': instance.bljg,
      'xmgm': instance.xmgm,
      'xmjd': instance.xmjd,
      'qtje': instance.qtje,
      'zgje': instance.zgje,
      'isgao': instance.isgao,
      'ktje': instance.ktje,
      'jyrsy': instance.jyrsy,
      'tqsyyj': instance.tqsyyj,
      'shijian': instance.shijian,
      'pic': instance.pic,
      'content': instance.content,
      'qxdw': instance.qxdw,
      'hkfs': instance.hkfs,
      'cishu': instance.cishu,
      'tzzt': instance.tzzt,
      'isft': instance.isft,
      'ftjl': instance.ftjl,
      'level': instance.level,
      'issy': instance.issy,
      'issj': instance.issj,
      'isdt': instance.isdt,
      'iswj': instance.iswj,
      'sort': instance.sort,
      'tzyq': instance.tzyq,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'cycle': instance.cycle,
      'istzbug': instance.istzbug,
      'isnew': instance.isnew,
      'doubled': instance.doubled,
      'countequity': instance.countequity,
      'bugunmber': instance.bugunmber,
      'ismake': instance.ismake,
      'endingtime': instance.endingtime,
      'isaouttm': instance.isaouttm,
      'interval_time': instance.intervalTime,
      'rise_time': instance.riseTime,
      'frequency': instance.frequency,
      'rise_settings': instance.riseSettings,
      'rise': instance.rise,
      'coupon': instance.coupon,
      'givecoupon': instance.givecoupon,
      'oldmoney': instance.oldmoney,
      'daikuan': instance.daikuan,
      'equity': instance.equity,
      'integralgive': instance.integralgive,
      'nextintegralgive': instance.nextintegralgive,
      'ticket': instance.ticket,
      'beans': instance.beans,
      'xxtcbl': instance.xxtcbl,
      'xxtcbll': instance.xxtcbll,
      'xxtcblll': instance.xxtcblll,
      'xxtcbllll': instance.xxtcbllll,
      'jiechuhetong': instance.jiechuhetong,
      'discount': instance.discount,
      'discountlist': instance.discountlist,
      'capital': instance.capital,
      'specialbenefits': instance.specialbenefits,
      'bjzk': instance.bjzk,
      'endtime': instance.endtime,
      'zengsongid': instance.zengsongid,
      'nextpid': instance.nextpid,
      'jfpid': instance.jfpid,
      'joining': instance.joining,
      'organizer': instance.organizer,
      'isgroup': instance.isgroup,
      'is_group_lerver': instance.isGroupLerver,
      'extmoney': instance.extmoney,
      'extday': instance.extday,
      'groupcbl': instance.groupcbl,
      'isnorate': instance.isnorate,
      'presale': instance.presale,
      'firstbuy': instance.firstbuy,
      'insurance': instance.insurance,
      'ft_after_success': instance.ftAfterSuccess,
      'present_level': instance.presentLevel,
      'return_dividends': instance.returnDividends,
      'return_capital': instance.returnCapital,
      'is_aggregated_amount': instance.isAggregatedAmount,
      'firstbuy_text': instance.firstbuyText,
      'invite_only': instance.inviteOnly,
      'dividend_method': instance.dividendMethod,
      'ismake2': instance.ismake2,
      'supportuse': instance.supportuse,
      'investgift': instance.investgift,
      'allreward': instance.allreward,
      'demand_tag_list': instance.demandTagList,
      'attention_tag_list': instance.attentionTagList,
      'group_demand_tag_list': instance.groupDemandTagList,
      'present_level_name': instance.presentLevelName,
      'present_level_text': instance.presentLevelText,
      'special_tag_list': instance.specialTagList,
    };

_$LinkImpl _$$LinkImplFromJson(Map<String, dynamic> json) => _$LinkImpl(
      url: json['url'] as String?,
      label: json['label'] as String?,
      active: json['active'] as bool?,
    );

Map<String, dynamic> _$$LinkImplToJson(_$LinkImpl instance) =>
    <String, dynamic>{
      'url': instance.url,
      'label': instance.label,
      'active': instance.active,
    };
